name: Check Proxies Availability

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  check-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and prepare subconverter
        run: |
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
          tar -xvf subconverter.tar.gz
          chmod +x subconverter/subconverter

      # --- ИСПРАВЛЕННЫЙ ШАГ ПРОВЕРКИ ---
      - name: Check proxies and save working ones
        run: |
          # Добавляем 2>/dev/null чтобы заглушить служебный вывод
          ./subconverter/subconverter -g -u "https://raw.githubusercontent.com/F0rc3Run/F0rc3Run/refs/heads/main/Best-Results/proxies.txt" --speedtest 300 2>/dev/null > public/checked-proxies.txt
        continue-on-error: true
        
      - name: Check if result file exists
        id: check_file
        run: |
          if [ -s public/checked-proxies.txt ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "No working proxies found. Skipping commit."
            echo "file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push checked proxies
        if: steps.check_file.outputs.file_exists == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Автоматическое обновление проверенных прокси"
          file_pattern: "public/checked-proxies.txt"
